# Generated by Django 3.1.4 on 2020-12-09 23:08

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post_image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('category', models.CharField(choices=[('1', "Men's causual apparell"), ('2', "Men's official apparell"), ('3', "Men's sports apparell"), ('4', "Men's casual shoes"), ('5', "Men's official shoes"), ('6', "Men's sports shoes"), ('7', "Women's causual apparell"), ('8', "Women's official apparell"), ('9', "Women's sports apparell"), ('10', "Women's casual shoes"), ('11', "women's official shoes"), ('12', "women's sports shoes"), ('13', "Kid's causual apparell"), ('14', "Kid's official apparell"), ('15', "Kid's sports apparell"), ('16', "Kid's shoes")], default='1', max_length=20)),
                ('contact', models.IntegerField()),
                ('contact_info', models.CharField(max_length=100)),
                ('Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
